language: ruby

services:
  - docker

before_install:
    - docker pull ubuntu:18.04
    - docker pull centos:centos7

install:
    - cd docker/ubuntu
    - docker build . -t ubuntu
    - cd -
    - cd docker/centos
    - docker build . -t centos
