# Jellybeans-like color theme

background = #181818
foreground = #dadada

# Normal colors (0-7)
palette = 0=#333333
palette = 1=#cb484c
palette = 2=#799d6a
palette = 3=#f5a25b
palette = 4=#4b73cc
palette = 5=#cc98de
palette = 6=#6f9cc2
palette = 7=#fafafa

# Bright colors (8-15)
palette = 8=#535353
palette = 9=#ef5350
palette = 10=#8bc34a
palette = 11=#ffd43b
palette = 12=#64b5f6
palette = 13=#eab1e7
palette = 14=#8ac7cf
palette = 15=#eaeaea

# Cursor colors
cursor-color = #cc98d3
